using System;
using System.Collections.Generic;

namespace CloudJourneyAddin.Models
{
    /// <summary>
    /// Represents an AI-generated enrollment plan with batched execution schedule
    /// </summary>
    public class EnrollmentPlan
    {
        /// <summary>
        /// Unique identifier for this plan
        /// </summary>
        public string PlanId { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// When this plan was generated
        /// </summary>
        public DateTime GeneratedDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Original goals that drove plan generation
        /// </summary>
        public EnrollmentGoals Goals { get; set; } = new EnrollmentGoals();

        /// <summary>
        /// Ordered list of enrollment batches
        /// </summary>
        public List<EnrollmentBatch> Batches { get; set; } = new List<EnrollmentBatch>();

        /// <summary>
        /// Total number of devices in this plan
        /// </summary>
        public int TotalDevices { get; set; }

        /// <summary>
        /// Estimated time to complete entire plan
        /// </summary>
        public TimeSpan EstimatedDuration { get; set; }

        /// <summary>
        /// AI explanation of why this plan was chosen
        /// </summary>
        public string AIReasoning { get; set; } = string.Empty;

        /// <summary>
        /// Current status of the plan
        /// </summary>
        public PlanStatus Status { get; set; } = PlanStatus.Generated;

        /// <summary>
        /// When the plan was approved (if applicable)
        /// </summary>
        public DateTime? ApprovedDate { get; set; }

        /// <summary>
        /// Who approved the plan
        /// </summary>
        public string? ApprovedBy { get; set; }

        /// <summary>
        /// When execution started
        /// </summary>
        public DateTime? ExecutionStartDate { get; set; }

        /// <summary>
        /// When execution completed
        /// </summary>
        public DateTime? ExecutionEndDate { get; set; }
    }

    /// <summary>
    /// Represents a single batch of devices to enroll together
    /// </summary>
    public class EnrollmentBatch
    {
        /// <summary>
        /// Sequence number (1, 2, 3, etc.)
        /// </summary>
        public int BatchNumber { get; set; }

        /// <summary>
        /// Device IDs to enroll in this batch
        /// </summary>
        public List<string> DeviceIds { get; set; } = new List<string>();

        /// <summary>
        /// Scheduled execution time for this batch
        /// </summary>
        public DateTime ScheduledTime { get; set; }

        /// <summary>
        /// AI justification for this batch composition
        /// </summary>
        public string Justification { get; set; } = string.Empty;

        /// <summary>
        /// Average readiness score for devices in this batch
        /// </summary>
        public double AverageRiskScore { get; set; }

        /// <summary>
        /// Status of this batch
        /// </summary>
        public BatchStatus Status { get; set; } = BatchStatus.Pending;

        /// <summary>
        /// When this batch started executing
        /// </summary>
        public DateTime? ActualStartTime { get; set; }

        /// <summary>
        /// When this batch completed
        /// </summary>
        public DateTime? ActualEndTime { get; set; }

        /// <summary>
        /// Number of devices successfully enrolled in this batch
        /// </summary>
        public int SuccessCount { get; set; }

        /// <summary>
        /// Number of devices that failed in this batch
        /// </summary>
        public int FailureCount { get; set; }
    }

    /// <summary>
    /// Status of an enrollment plan
    /// </summary>
    public enum PlanStatus
    {
        /// <summary>
        /// Plan generated by AI, awaiting approval
        /// </summary>
        Generated,

        /// <summary>
        /// Plan approved and ready to execute
        /// </summary>
        Approved,

        /// <summary>
        /// Plan is currently executing
        /// </summary>
        Executing,

        /// <summary>
        /// Plan paused (emergency stop or auto-pause)
        /// </summary>
        Paused,

        /// <summary>
        /// Plan completed successfully
        /// </summary>
        Completed,

        /// <summary>
        /// Plan failed with critical errors
        /// </summary>
        Failed,

        /// <summary>
        /// Plan cancelled by user
        /// </summary>
        Cancelled
    }

    /// <summary>
    /// Status of an individual batch
    /// </summary>
    public enum BatchStatus
    {
        /// <summary>
        /// Not yet started
        /// </summary>
        Pending,

        /// <summary>
        /// Currently executing
        /// </summary>
        InProgress,

        /// <summary>
        /// Completed successfully
        /// </summary>
        Completed,

        /// <summary>
        /// Completed with some failures
        /// </summary>
        CompletedWithErrors,

        /// <summary>
        /// Failed to execute
        /// </summary>
        Failed,

        /// <summary>
        /// Skipped due to previous failures
        /// </summary>
        Skipped
    }
}
