<#
.SYNOPSIS
    Generates ApplicationFiles.wxs for WiX v4+ with proper subdirectory handling
.DESCRIPTION
    Since WiX v6 does not include Heat as a standalone tool, this script
    generates the ApplicationFiles.wxs component file with proper directory structure.
#>

param(
    [string]$PublishPath = "..\bin\Release\net8.0-windows\win-x64\publish",
    [string]$OutputFile = "ApplicationFiles.wxs"
)

$ErrorActionPreference = "Stop"

Write-Host "Generating $OutputFile from $PublishPath..."

$resolvedPath = Resolve-Path $PublishPath
$files = Get-ChildItem -Path $resolvedPath -Recurse -File
Write-Host "Found $($files.Count) files to include"

# Group files by their relative directory
$filesByDir = @{}
foreach ($file in $files) {
    $relativePath = $file.FullName.Replace($resolvedPath.Path, "").TrimStart("\")
    $relativeDir = Split-Path -Path $relativePath -Parent
    if ([string]::IsNullOrEmpty($relativeDir)) {
        $relativeDir = "."
    }
    if (-not $filesByDir.ContainsKey($relativeDir)) {
        $filesByDir[$relativeDir] = @()
    }
    $filesByDir[$relativeDir] += $file
}

# Start WXS file with proper WiX v4 format
$wxsContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by Generate-ApplicationFiles.ps1 -->
<!-- Do not edit manually - regenerate with: .\Generate-ApplicationFiles.ps1 -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">

"@

# Track all directory IDs for directory definitions
$directories = @{}
$componentRefs = [System.Collections.ArrayList]::new()
$fileId = 0

# Process each directory
foreach ($dir in $filesByDir.Keys | Sort-Object) {
    $dirFiles = $filesByDir[$dir]
    
    if ($dir -eq ".") {
        # Root directory files go directly under INSTALLFOLDER
        foreach ($f in $dirFiles) {
            $fileId++
            $componentId = "cmp_$fileId"
            $fileIdStr = "fil_$fileId"
            $sourcePath = "`$(var.PublishDir)\$($f.Name)"
            
            [void]$componentRefs.Add("            <ComponentRef Id=`"$componentId`" />")
            
            $wxsContent += @"
    <Fragment>
        <ComponentGroup Id="AppFiles_$fileId" Directory="INSTALLFOLDER">
            <Component Id="$componentId" Guid="*">
                <File Id="$fileIdStr" Source="$sourcePath" KeyPath="yes" />
            </Component>
        </ComponentGroup>
    </Fragment>

"@
        }
    } else {
        # Subdirectory - create directory ID
        $dirId = "dir_" + ($dir -replace "[^a-zA-Z0-9]", "_")
        $directories[$dir] = $dirId
        
        foreach ($f in $dirFiles) {
            $fileId++
            $componentId = "cmp_$fileId"
            $fileIdStr = "fil_$fileId"
            $relativePath = $f.FullName.Replace($resolvedPath.Path, "").TrimStart("\")
            $sourcePath = "`$(var.PublishDir)\$relativePath"
            
            [void]$componentRefs.Add("            <ComponentRef Id=`"$componentId`" />")
            
            $wxsContent += @"
    <Fragment>
        <ComponentGroup Id="AppFiles_$fileId" Directory="$dirId">
            <Component Id="$componentId" Guid="*">
                <File Id="$fileIdStr" Source="$sourcePath" KeyPath="yes" />
            </Component>
        </ComponentGroup>
    </Fragment>

"@
        }
    }
}

# Add directory definitions
$wxsContent += @"
    <!-- Directory definitions for subdirectories -->
    <Fragment>
        <DirectoryRef Id="INSTALLFOLDER">

"@

foreach ($dir in $directories.Keys | Sort-Object) {
    $dirId = $directories[$dir]
    $dirName = Split-Path -Path $dir -Leaf
    $wxsContent += @"
            <Directory Id="$dirId" Name="$dirName" />

"@
}

$wxsContent += @"
        </DirectoryRef>
    </Fragment>

"@

# Add main component group that references all files
$wxsContent += @"
    <!-- Main component group referencing all application files -->
    <Fragment>
        <ComponentGroup Id="ApplicationFiles">
$($componentRefs -join "`r`n")
        </ComponentGroup>
    </Fragment>
</Wix>
"@

# Write file with UTF-8 encoding (no BOM for WiX compatibility)
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Join-Path (Get-Location) $OutputFile), $wxsContent, $utf8NoBom)

$lineCount = ($wxsContent -split "`n").Count
Write-Host "Generated $OutputFile with $fileId components in $($directories.Count + 1) directories ($lineCount lines)" -ForegroundColor Green
